services:
  postgres:
    image: postgres:latest
    container_name: piscineds_postgres
    environment:
      POSTGRES_USER: lmattern
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./item:/item:ro
      - ./customer:/customer:ro
      - ./ex02:/ex02:rw
      - ./ex03:/ex03:rw
      - ./ex04:/ex04:rw
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: piscineds_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: lmattern@student.42.fr
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - ./item:/item:ro
      - ./customer:/customer:ro
      - ./ex02:/ex02:rw
      - ./ex03:/ex03:rw
      - ./ex04:/ex04:rw
    restart: unless-stopped

volumes:
  postgres_data:
